# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uitable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uitable
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 5.2'
    pod 'SnapKit', '~> 5.0.1'
    pod 'Kingfisher', '~> 6.0'
    pod 'ESPullToRefresh'
   

end
