# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sob_blog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sob_blog
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 5.2'
    pod 'SnapKit', '~> 5.0.1'
    pod 'Kingfisher', '~> 6.0'
  target 'sob_blogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sob_blogUITests' do
    # Pods for testing
  end

end
